import type {
  ArrangementVersion,
  Artifact,
  CostEstimate,
  DirectorActionId,
  DirectorActionResult,
  DirectorSuggestion,
  ProcessingGoal,
  ProcessingJob,
  ProcessingStep,
  Project,
  Scenario,
  ShareRecipient,
  SongAnalysis,
} from "./types";

export const processingGoals: ProcessingGoal[] = [
  {
    id: "band-analysis",
    scenario: "band",
    label: "Разобрать песню",
    description: "Понять форму, тональность, аккорды, партии и сомнительные места.",
    expectedOutputs: ["Форма", "Аккорды", "Партии", "Сомнительные такты"],
  },
  {
    id: "band-rehearsal",
    scenario: "band",
    label: "Подготовить репетицию",
    description: "Собрать материалы для всей группы и репетиционные треки.",
    expectedOutputs: ["Stage Pack", "Партии", "Минус", "Клик"],
  },
  {
    id: "band-performance",
    scenario: "band",
    label: "Подготовить выступление",
    description: "Сделать концертную версию с акцентами, концовкой и выдачей материалов.",
    expectedOutputs: ["Концертная версия", "Партии", "ZIP", "История правок"],
  },
  {
    id: "band-minus",
    scenario: "band",
    label: "Сделать минус",
    description: "Подготовить аудиослои, минус и треки без выбранного инструмента.",
    expectedOutputs: ["Аудиослои", "Минус", "Репетиционные треки"],
  },
  {
    id: "band-parts",
    scenario: "band",
    label: "Разложить на партии",
    description: "Собрать ноты, TAB, MIDI и материалы по инструментам.",
    expectedOutputs: ["Ноты", "TAB", "MIDI", "PDF"],
  },
  {
    id: "band-transpose",
    scenario: "band",
    label: "Транспонировать под вокал",
    description: "Подогнать тональность под диапазон вокалиста.",
    expectedOutputs: ["Новая тональность", "Обновленные партии"],
  },
  {
    id: "band-adapt-lineup",
    scenario: "band",
    label: "Адаптировать под состав",
    description: "Перенести недоступные партии на реальные инструменты группы.",
    expectedOutputs: ["План адаптации", "Новые партии"],
  },
  {
    id: "band-boost",
    scenario: "band",
    label: "Усилить припев",
    description: "Добавить энергию в припев или концертную концовку.",
    expectedOutputs: ["Усиленный припев", "Концертная концовка"],
  },
  {
    id: "lesson-analysis",
    scenario: "education",
    label: "Разобрать на уроке",
    description: "Показать форму, аккорды, трудные места и что слушать в оригинале.",
    expectedOutputs: ["Разбор", "Заметки преподавателя", "Домашка"],
  },
  {
    id: "lesson-easy",
    scenario: "education",
    label: "Сделать простую версию",
    description: "Снизить сложность партии под уровень ученика.",
    expectedOutputs: ["Easy", "Партия ученика", "Домашка"],
  },
  {
    id: "lesson-original",
    scenario: "education",
    label: "Близко к оригиналу",
    description: "Сохранить характер песни и убрать только лишнюю сложность.",
    expectedOutputs: ["Original-like", "Разбор", "Партия ученика"],
  },
  {
    id: "lesson-advanced",
    scenario: "education",
    label: "Усложнить для сильного ученика",
    description: "Добавить выразительность, вариации и более богатую партию.",
    expectedOutputs: ["Advanced", "Вариации", "Проверочные такты"],
  },
  {
    id: "lesson-concert",
    scenario: "education",
    label: "Усилить для концерта",
    description: "Сделать школьную концертную версию с несколькими ролями.",
    expectedOutputs: ["Концертная версия", "Ансамбль", "Минус"],
  },
  {
    id: "lesson-ensemble",
    scenario: "education",
    label: "Разложить на ансамбль",
    description: "Раздать материал нескольким ученикам по уровню и инструментам.",
    expectedOutputs: ["Ансамблевые партии", "Версии учеников"],
  },
  {
    id: "lesson-homework",
    scenario: "education",
    label: "Домашнее задание",
    description: "Подготовить короткие упражнения и трек для самостоятельной практики.",
    expectedOutputs: ["Задания", "Клик", "Минус"],
  },
  {
    id: "lesson-practice-tracks",
    scenario: "education",
    label: "Минус и подсказки",
    description: "Собрать фонограмму, клик и подсказки по форме.",
    expectedOutputs: ["Минус", "Клик", "Cue track"],
  },
];

export const directorActionResults: Record<DirectorActionId, DirectorActionResult> = {
  "transpose-down-2": {
    versionLabel: "Транспозиция под вокал",
    versionKind: "band",
    historyTitle: "Песня транспонирована на два полутона вниз",
    changes: ["Тональность перенесена на два полутона ниже.", "Вокальная кульминация стала ближе к выбранному диапазону."],
    staleArtifactTypes: ["score", "part", "tab", "chords", "lyrics", "midi", "zip"],
  },
  "merge-guitars": {
    versionLabel: "Одна гитара",
    versionKind: "band",
    historyTitle: "Гитарные партии объединены для одного гитариста",
    changes: ["Рифф оставлен в куплетах.", "В припеве сохранены акценты второй гитары."],
    staleArtifactTypes: ["score", "part", "tab", "midi", "zip"],
  },
  "move-strings-to-keys": {
    versionLabel: "Strings на клавишах",
    versionKind: "band",
    historyTitle: "Струнные перенесены на клавиши",
    changes: ["Партия strings переложена на правую руку.", "В припеве добавлен pad-слой."],
    staleArtifactTypes: ["score", "part", "midi", "zip"],
  },
  "simplify-drums": {
    versionLabel: "Барабаны проще",
    versionKind: "easy",
    historyTitle: "Барабаны упрощены",
    changes: ["Филлы заменены на устойчивый groove.", "Синкопы оставлены только в переходах."],
    staleArtifactTypes: ["score", "part", "midi", "practice", "zip"],
  },
  "beginner-bass": {
    versionLabel: "Бас начального уровня",
    versionKind: "easy",
    historyTitle: "Создана простая басовая партия",
    changes: ["Партия держит тоники и основные подходы.", "Сложные проходящие ноты вынесены в advanced-заметки."],
    staleArtifactTypes: ["score", "part", "midi", "practice", "zip"],
  },
  "boost-chorus": {
    versionLabel: "Усиленный припев",
    versionKind: "concert",
    historyTitle: "AI-директор усилил припев",
    changes: ["Клавиши дублируют hook в припеве.", "Барабаны получают открытый hi-hat.", "В концовке добавлен концертный стоп."],
    staleArtifactTypes: ["score", "part", "midi", "practice", "zip"],
  },
  "practice-without-bass": {
    versionLabel: "Трек без баса",
    versionKind: "band",
    historyTitle: "Создан репетиционный трек без баса",
    changes: ["Бас приглушен в тренировочном миксе.", "Клик оставлен только в интро и бридже."],
    staleArtifactTypes: ["practice", "zip"],
  },
  "education-version": {
    versionLabel: "Учебная версия",
    versionKind: "easy",
    historyTitle: "Создана учебная версия",
    changes: ["Оставлены куплет и припев.", "Ритм упрощен до восьмых.", "Добавлены заметки преподавателя."],
    staleArtifactTypes: ["score", "part", "student", "teacher", "practice", "zip"],
  },
  "advanced-student-part": {
    versionLabel: "Advanced для сильного ученика",
    versionKind: "advanced",
    historyTitle: "Создана усложненная партия для сильного ученика",
    changes: ["Добавлены проходящие ноты.", "Во втором припеве появилась ритмическая вариация.", "Сложные такты отмечены для проверки."],
    staleArtifactTypes: ["score", "part", "student", "teacher", "midi", "zip"],
  },
  "student-ensemble": {
    versionLabel: "Ансамбль учеников",
    versionKind: "ensemble",
    historyTitle: "Песня разложена на ансамбль учеников",
    changes: ["Мелодия разделена между гитарой и клавишами.", "Перкуссия получила простую пульсацию.", "Каждому ученику назначена отдельная партия."],
    staleArtifactTypes: ["score", "part", "student", "teacher", "practice", "zip"],
  },
  "lesson-analysis": {
    versionLabel: "Разбор для урока",
    versionKind: "original-like",
    historyTitle: "Подготовлен разбор песни для урока",
    changes: ["Добавлена форма песни.", "Отмечены трудные аккорды.", "Сформировано домашнее задание на припев."],
    staleArtifactTypes: ["teacher", "student", "chords", "lyrics", "zip"],
  },
};

export const directorSuggestions: DirectorSuggestion[] = [
  {
    id: "suggest-boost",
    title: "Припев можно сделать сильнее",
    description: "Сейчас один гитарист и клавиши могут не удержать энергию оригинала.",
    actionId: "boost-chorus",
    scenario: "band",
    impact: "arrangement",
  },
  {
    id: "suggest-guitars",
    title: "В оригинале две гитары",
    description: "Можно объединить рифф и акценты в одну партию с TAB.",
    actionId: "merge-guitars",
    scenario: "band",
    impact: "arrangement",
  },
  {
    id: "suggest-keys",
    title: "Струнные можно отдать клавишам",
    description: "Партия strings важна в припеве, но отдельного струнного состава нет.",
    actionId: "move-strings-to-keys",
    scenario: "band",
    impact: "arrangement",
  },
  {
    id: "suggest-advanced",
    title: "Ученик готов к версии сложнее",
    description: "Можно добавить проходящие ноты и вариацию во втором припеве.",
    actionId: "advanced-student-part",
    scenario: "education",
    impact: "education",
  },
  {
    id: "suggest-ensemble",
    title: "Материал подходит для ансамбля",
    description: "Мелодию, басовую опору и ритм можно раздать разным ученикам.",
    actionId: "student-ensemble",
    scenario: "education",
    impact: "education",
  },
  {
    id: "suggest-lesson",
    title: "Сделать разбор для урока",
    description: "Форма, аккорды и трудные такты попадут в версию преподавателя.",
    actionId: "lesson-analysis",
    scenario: "education",
    impact: "review",
  },
];

const baseSteps: ProcessingStep[] = [
  { id: "normalize", label: "Нормализация аудио", status: "queued", detail: "Проверяем формат и уровень громкости." },
  { id: "stems", label: "Разделение на аудиослои", status: "queued", detail: "Имитируем вокал, барабаны, бас, гитару и клавиши." },
  { id: "tempo", label: "BPM, тональность и размер", status: "queued", detail: "Ищем пульс, тональный центр и смены метра." },
  { id: "structure", label: "Структура песни", status: "queued", detail: "Собираем intro, куплеты, припевы, bridge и coda." },
  { id: "chords", label: "Аккорды", status: "queued", detail: "Строим черновую аккордовую сетку." },
  { id: "midi", label: "MIDI-черновики", status: "queued", detail: "Переводим важные аудиослои в MIDI-партии." },
  { id: "notation", label: "MusicXML и PDF", status: "queued", detail: "Готовим ноты и карточки страниц." },
  { id: "director", label: "Ревью AI-директора", status: "queued", detail: "Ищем проблемы состава, уровня и выдачи материалов." },
];

export const processingStepIds: string[] = baseSteps.map((step) => step.id);

export const processingMilestones: Array<{ label: string; detail: string; stepIds: string[] }> = [
  { label: "Аудио", detail: "файл, громкость, слои", stepIds: ["normalize", "stems"] },
  { label: "Форма", detail: "BPM, тональность, части песни", stepIds: ["tempo", "structure", "chords"] },
  { label: "Партии", detail: "MIDI, ноты, материалы", stepIds: ["midi", "notation"] },
  { label: "Ревью", detail: "что проверить руками", stepIds: ["director"] },
];

const bandAnalysis: SongAnalysis = {
  title: "Late Train Home",
  artist: "Demo Cover",
  bpm: 104,
  key: "G minor",
  meter: "4/4",
  duration: "3:42",
  genre: "pop/rock",
  summary: "Песня держится на плотном припеве, вокальном hook и двух гитарных слоях. Для одного гитариста нужна адаптация.",
  confidenceByPart: {
    Вокал: 0.91,
    Барабаны: 0.88,
    Бас: 0.84,
    Гитара: 0.72,
    Клавиши: 0.78,
  },
  sections: [
    { id: "intro", label: "Intro", startBar: 1, endBar: 4, note: "Гитарный рифф и короткий pickup." },
    { id: "verse-1", label: "Куплет 1", startBar: 5, endBar: 20, note: "Вокал ниже, бас играет простую опору." },
    { id: "chorus-1", label: "Припев 1", startBar: 21, endBar: 36, note: "Струнный слой и вторая гитара добавляют энергию." },
    { id: "bridge", label: "Bridge", startBar: 37, endBar: 44, note: "Пауза перед возвратом припева." },
    { id: "chorus-2", label: "Припев 2", startBar: 45, endBar: 60, note: "Концертную концовку можно усилить стопом." },
  ],
  chords: [
    { bar: 1, beat: 1, chord: "Gm", confidence: 0.92 },
    { bar: 3, beat: 1, chord: "Eb", confidence: 0.87 },
    { bar: 5, beat: 1, chord: "Bb", confidence: 0.89 },
    { bar: 7, beat: 1, chord: "F", confidence: 0.9 },
    { bar: 21, beat: 1, chord: "Eb", confidence: 0.74 },
    { bar: 23, beat: 1, chord: "Bb", confidence: 0.81 },
    { bar: 37, beat: 1, chord: "Cm", confidence: 0.68 },
    { bar: 45, beat: 1, chord: "Gm", confidence: 0.86 },
  ],
};

const lessonAnalysis: SongAnalysis = {
  title: "Warm Lights",
  artist: "Demo Lesson",
  bpm: 92,
  key: "C major",
  meter: "4/4",
  duration: "2:58",
  genre: "acoustic pop",
  summary: "Песня удобна для урока гитары: простая форма, ясные аккорды, один сложный переход перед припевом.",
  confidenceByPart: {
    Мелодия: 0.88,
    Аккорды: 0.9,
    Гитара: 0.82,
    Бас: 0.75,
  },
  sections: [
    { id: "lesson-intro", label: "Intro", startBar: 1, endBar: 4, note: "Можно пропустить для первой домашки." },
    { id: "lesson-verse", label: "Куплет", startBar: 5, endBar: 20, note: "Основной паттерн правой руки." },
    { id: "lesson-chorus", label: "Припев", startBar: 21, endBar: 36, note: "Подходит для первой цельной версии." },
    { id: "lesson-outro", label: "Outro", startBar: 37, endBar: 40, note: "Сокращенная концовка для урока." },
  ],
  chords: [
    { bar: 1, beat: 1, chord: "C", confidence: 0.94 },
    { bar: 3, beat: 1, chord: "Am", confidence: 0.92 },
    { bar: 5, beat: 1, chord: "F", confidence: 0.89 },
    { bar: 7, beat: 1, chord: "G", confidence: 0.91 },
    { bar: 21, beat: 1, chord: "Dm", confidence: 0.77 },
    { bar: 23, beat: 1, chord: "G", confidence: 0.9 },
  ],
};

const ensembleAnalysis: SongAnalysis = {
  title: "School Hall",
  artist: "Demo Ensemble",
  bpm: 118,
  key: "D major",
  meter: "4/4",
  duration: "3:16",
  genre: "school concert pop",
  summary: "Материал можно разложить на гитару, клавиши, перкуссию и вокальный ответ. В припеве нужен крупный сценический вид.",
  confidenceByPart: {
    Вокал: 0.86,
    Гитара: 0.8,
    Клавиши: 0.83,
    Перкуссия: 0.88,
  },
  sections: [
    { id: "ensemble-intro", label: "Intro", startBar: 1, endBar: 8, note: "Клавиши дают вступление, перкуссия входит с 5 такта." },
    { id: "ensemble-verse", label: "Куплет", startBar: 9, endBar: 24, note: "Гитара держит аккорды, вокал отвечает короткими фразами." },
    { id: "ensemble-chorus", label: "Припев", startBar: 25, endBar: 40, note: "Можно добавить второй голос и хлопки." },
    { id: "ensemble-coda", label: "Coda", startBar: 41, endBar: 48, note: "Нелинейная концовка с повтором последней строки." },
  ],
  chords: [
    { bar: 1, beat: 1, chord: "D", confidence: 0.91 },
    { bar: 5, beat: 1, chord: "G", confidence: 0.88 },
    { bar: 9, beat: 1, chord: "Bm", confidence: 0.82 },
    { bar: 13, beat: 1, chord: "A", confidence: 0.9 },
    { bar: 25, beat: 1, chord: "G", confidence: 0.8 },
    { bar: 29, beat: 1, chord: "D", confidence: 0.88 },
    { bar: 41, beat: 1, chord: "A/C#", confidence: 0.67 },
  ],
};

const readyProcessing = (id: string): ProcessingJob => ({
  id,
  status: "ready",
  steps: baseSteps.map((step, index) => ({
    ...step,
    status: index === 3 ? "warning" : "done",
  })),
  warnings: ["Секция bridge содержит паузу и может потребовать ручной проверки.", "Гитарный stem плотный: TAB будет черновиком."],
  progressPercent: 100,
});

export const createQueuedProcessing = (id: string): ProcessingJob => ({
  id,
  status: "queued",
  steps: baseSteps.map((step) => ({ ...step })),
  warnings: ["Результат будет черновиком для проверки музыкантом."],
  progressPercent: 0,
});

const version = (id: string, label: string, kind: ArrangementVersion["kind"], changes: string[]): ArrangementVersion => ({
  id,
  label,
  kind,
  createdAt: "2026-09-09T12:00:00+04:00",
  createdBy: "AI-директор",
  status: "needs_review",
  changes,
});

const artifacts = (scenario: Scenario): Artifact[] => [
  {
    id: "full-score",
    type: "score",
    name: "Общая партитура",
    format: "PDF",
    description: "Черновая партитура для проверки формы, аккордов и партий.",
    status: "needs_review",
    confidence: 0.82,
    audience: "all",
    isStale: false,
    preview: { kind: "notation", title: "Партитура", lines: ["1 | Gm | Eb | Bb | F", "21 | Eb | Bb | F | Gm", "37 | Cm | Eb | пауза | D"] },
  },
  {
    id: "vocal-part",
    type: "part",
    name: "Партия вокала",
    format: "PDF",
    description: "Мелодия, текст, диапазон и дыхание.",
    status: "draft",
    confidence: 0.91,
    audience: scenario === "education" ? "student" : "instrument",
    isStale: false,
    preview: { kind: "notation", title: "Вокал", lines: ["Куплет: спокойная тесситура", "Припев: кульминация на верхней ноте", "Bridge: проверить вход после паузы"] },
  },
  {
    id: "guitar-tab",
    type: "tab",
    name: "Гитара + TAB",
    format: "PDF",
    description: "Рифф, аккорды и удобная аппликатура.",
    status: "needs_review",
    confidence: 0.72,
    audience: "instrument",
    isStale: false,
    preview: { kind: "notation", title: "Гитара", lines: ["Intro: рифф на 3 струне", "Припев: акценты второй гитары отмечены", "TAB: такты 21-24 требуют проверки"] },
  },
  {
    id: "bass-part",
    type: "part",
    name: "Бас",
    format: "PDF",
    description: "Басовая линия с ограничением диапазона.",
    status: "ready",
    confidence: 0.84,
    audience: "instrument",
    isStale: false,
    preview: { kind: "notation", title: "Бас", lines: ["Куплет: тоника и пятая", "Припев: движение к Eb", "Coda: оставить простую опору"] },
  },
  {
    id: "chord-chart",
    type: "chords",
    name: "Таблица аккордов",
    format: "PDF",
    description: "Секции, такты и аккорды для быстрой репетиции.",
    status: "draft",
    confidence: 0.86,
    audience: "all",
    isStale: false,
    preview: { kind: "text", title: "Аккорды", lines: ["Intro: Gm | Eb | Bb | F", "Verse: Bb | F | Gm | Eb", "Chorus: Eb | Bb | F | Gm"] },
  },
  {
    id: "midi-full",
    type: "midi",
    name: "Общий MIDI",
    format: "MIDI",
    description: "Черновой MIDI для проверки партий.",
    status: "draft",
    confidence: 0.76,
    audience: "all",
    isStale: false,
    preview: { kind: "midi", title: "MIDI дорожки", lines: ["Vocal: 78 нот", "Bass: 142 события", "Keys: 4 слоя", "Drums: groove + fills"] },
  },
  {
    id: "stems",
    type: "stem",
    name: "Аудиослои",
    format: "WAV",
    description: "Вокал, барабаны, бас, гитара, клавиши и прочие слои.",
    status: "ready",
    confidence: 0.87,
    audience: "all",
    isStale: false,
    preview: { kind: "waveform", title: "Аудиослои", lines: ["Вокал", "Барабаны", "Бас", "Гитара", "Клавиши", "Прочее"] },
  },
  {
    id: "minus-track",
    type: "minus",
    name: "Минус",
    format: "WAV",
    description: "Тренировочный микс без основного вокала.",
    status: "ready",
    confidence: 0.88,
    audience: "all",
    isStale: false,
    preview: { kind: "waveform", title: "Минус", lines: ["Intro", "Verse", "Chorus", "Bridge", "Chorus"] },
  },
  {
    id: "click-track",
    type: "click",
    name: "Клик",
    format: "WAV",
    description: "Клик с подсказками входов.",
    status: "ready",
    confidence: 0.93,
    audience: "all",
    isStale: false,
    preview: { kind: "waveform", title: "Клик", lines: ["Count-in 2 bars", "Bridge cue", "Final stop"] },
  },
  {
    id: "practice-bass",
    type: "practice",
    name: "Репетиционный трек без баса",
    format: "WAV",
    description: "Трек для самостоятельной практики басиста.",
    status: "ready",
    confidence: 0.84,
    audience: "instrument",
    isStale: false,
    preview: { kind: "waveform", title: "Без баса", lines: ["Vocals", "Drums", "Guitar", "Keys", "Click cue"] },
  },
  {
    id: scenario === "education" ? "student-pack" : "zip-pack",
    type: scenario === "education" ? "student" : "zip",
    name: scenario === "education" ? "Версия ученика" : "Общий ZIP",
    format: scenario === "education" ? "PDF" : "ZIP",
    description: scenario === "education" ? "Партия, подсказки и домашнее задание." : "Все материалы Stage Pack одним пакетом.",
    status: "ready",
    confidence: 0.86,
    audience: scenario === "education" ? "student" : "all",
    isStale: false,
    preview: { kind: "bundle", title: scenario === "education" ? "Пакет ученика" : "ZIP", lines: ["Full Score.pdf", "Chords.pdf", "MIDI.mid", "Minus.wav", "Click.wav"] },
  },
  ...(scenario === "education"
    ? [
        {
          id: "teacher-notes",
          type: "teacher" as const,
          name: "Заметки преподавателя",
          format: "PDF" as const,
          description: "Форма, сложные места, домашка и подсказки по уроку.",
          status: "draft" as const,
          confidence: 0.88,
          audience: "teacher" as const,
          isStale: false,
          preview: { kind: "text" as const, title: "Заметки", lines: ["Цель урока: уверенный переход в припев", "Домашка: 8 тактов медленно с кликом", "Проверить: Dm -> G"] },
        },
      ]
    : []),
];

const bandRecipients: ShareRecipient[] = [
  { id: "vocalist-1", name: "Оксана", role: "vocalist", material: "Вокал + текст", status: "opened" },
  { id: "guitarist-1", name: "Илья", role: "guitarist", material: "Гитара + TAB", status: "not_issued" },
  { id: "bassist-1", name: "Марк", role: "bassist", material: "Бас + трек без баса", status: "not_issued" },
  { id: "keys-1", name: "Лена", role: "keys", material: "Клавиши + струнный слой", status: "needs_fix" },
  { id: "drummer-1", name: "Даня", role: "drummer", material: "Партия барабанов + клик", status: "not_issued" },
];

const educationRecipients: ShareRecipient[] = [
  { id: "student-1", name: "Аня", role: "student", material: "Партия ученика", status: "not_issued" },
  { id: "student-2", name: "Миша", role: "student", material: "Клавиши easy", status: "not_issued" },
  { id: "student-3", name: "Соня", role: "student", material: "Перкуссия", status: "opened" },
  { id: "teacher-1", name: "Преподаватель", role: "teacher", material: "Версия преподавателя", status: "opened" },
];

const cost = (complexity: CostEstimate["complexity"], credits: number): CostEstimate => ({
  tier: complexity === "high" ? "multi_version" : "fast_draft",
  complexity,
  credits,
  notes: [
    "Оценка демонстрационная.",
    "Сложность зависит от длительности, аудиослоев, партий и повторной обработки.",
  ],
});

export const demoProjects: Project[] = [
  {
    id: "band-demo",
    name: "Late Train Home: подготовка к репетиции",
    scenario: "band",
    processingGoal: processingGoals.find((goal) => goal.id === "band-rehearsal")!,
    upload: { id: "upload-band-demo", fileName: "late-train-home-demo.mp3", format: "DEMO", durationSeconds: 222, quality: "medium", sourceNote: "Демо без реального аудиофайла." },
    bandLineup: {
      leadVocal: true,
      vocalRange: "A2-E4",
      guitars: 1,
      guitarTuning: "Standard E",
      capo: "нет",
      bass: "4 strings",
      keys: true,
      keysCanCoverLayers: true,
      drums: true,
      backingVocals: false,
      musicianLevel: "middle",
      targetStyle: "плотнее и сценически",
    },
    assignments: [],
    versions: [
      version("original", "Оригинал", "original", ["Исходная структура и найденные партии."]),
      version("band-main", "Для группы", "band", ["Две гитары сведены в рабочий черновик.", "Струнные отмечены для переноса на клавиши."]),
    ],
    currentVersionId: "band-main",
    processing: readyProcessing("job-band-demo"),
    analysis: bandAnalysis,
    stagePack: { id: "stage-band-demo", versionId: "band-main", artifacts: artifacts("band") },
    reviewIssues: [
      { id: "issue-guitar-21", title: "Проверить гитарный акцент", sectionId: "chorus-1", bar: 21, part: "Гитара", reason: "Stem содержит две гитары, TAB может смешивать партии.", status: "needs_review", confidence: 0.62 },
      { id: "issue-bridge-37", title: "Пауза перед bridge", sectionId: "bridge", bar: 37, part: "Вся группа", reason: "Найдено резкое падение энергии и возможная остановка.", status: "uncertain", confidence: 0.58 },
    ],
    reviewComments: [],
    directorSuggestions: directorSuggestions.filter((suggestion) => suggestion.scenario !== "education"),
    chat: [{ id: "chat-1", author: "director", text: "Я нашел две гитарные партии и струнный слой в припеве. Для вашего состава лучше сделать концертную версию.", createdAt: "2026-09-09T12:04:00+04:00" }],
    changeLog: [{ id: "change-1", title: "Создан Stage Pack", description: "Подготовлены партии, аудиослои, MIDI и первые предупреждения.", createdAt: "2026-09-09T12:05:00+04:00", actor: "AI-директор" }],
    shareRecipients: bandRecipients,
    shareLinks: [],
    exportBundles: [{ id: "zip-band", label: "Stage Pack ZIP", filesCount: 14, status: "ready" }],
    costEstimate: cost("medium", 7),
    setupSnapshot: {
      scenario: "band",
      title: "Состав группы",
      fields: [
        { label: "Диапазон вокала", value: "A2-E4" },
        { label: "Гитаристов", value: "1" },
        { label: "Бас", value: "4 струны" },
        { label: "Клавиши", value: "да, закрывают слои" },
        { label: "Стиль версии", value: "плотнее и сценически" },
      ],
    },
    legalConsent: { accepted: true, text: "Материал используется для приватной репетиции или внутренней подготовки.", acceptedAt: "2026-09-09T12:00:00+04:00" },
    dataRetention: { sourceDeleted: false, resultsDeleted: false, retentionNote: "Исходник и результаты можно удалить из проекта." },
  },
  {
    id: "education-lesson-demo",
    name: "Warm Lights: урок гитары",
    scenario: "education",
    processingGoal: processingGoals.find((goal) => goal.id === "lesson-easy")!,
    upload: { id: "upload-lesson-demo", fileName: "warm-lights-demo.m4a", format: "DEMO", durationSeconds: 178, quality: "good", sourceNote: "Демо без реального аудиофайла." },
    studentProfile: { name: "Аня", instrument: "Гитара", level: "начальный", ageGroup: "10-12", notationReading: "простые ноты", chordKnowledge: "C, Am, F, G", homeInstrument: "акустическая гитара" },
    teacherProfile: { name: "Оксана", format: "индивидуальный урок", focus: "переходы аккордов и ровный ритм" },
    lesson: { goal: "сыграть куплет и припев с кликом", homeworkFormat: "короткий PDF + минус", desiredDifficulty: "проще оригинала" },
    assignments: [{ id: "assignment-1", title: "8 тактов припева с кликом", recipient: "Аня", status: "assigned" }],
    versions: [
      version("lesson-original", "Оригинал", "original", ["Исходная форма песни."]),
      version("lesson-easy", "Easy", "easy", ["Оставлены куплет и припев.", "Ритм правой руки упрощен."]),
    ],
    currentVersionId: "lesson-easy",
    processing: readyProcessing("job-lesson-demo"),
    analysis: lessonAnalysis,
    stagePack: { id: "stage-lesson-demo", versionId: "lesson-easy", artifacts: artifacts("education") },
    reviewIssues: [
      { id: "issue-dm-21", title: "Переход Dm-G", sectionId: "lesson-chorus", bar: 21, part: "Гитара", reason: "Для начального уровня переход может быть слишком быстрым.", status: "needs_review", confidence: 0.7 },
    ],
    reviewComments: [],
    directorSuggestions: directorSuggestions.filter((suggestion) => suggestion.scenario !== "band"),
    chat: [{ id: "chat-lesson-1", author: "director", text: "Для урока лучше оставить куплет и припев, а сложный переход вынести в отдельное упражнение.", createdAt: "2026-09-09T12:06:00+04:00" }],
    changeLog: [{ id: "change-lesson-1", title: "Создана Easy-версия", description: "Сокращена форма и подготовлена домашка.", createdAt: "2026-09-09T12:07:00+04:00", actor: "AI-директор" }],
    shareRecipients: educationRecipients,
    shareLinks: [],
    exportBundles: [{ id: "zip-lesson", label: "Пакет урока", filesCount: 8, status: "ready" }],
    costEstimate: cost("low", 4),
    setupSnapshot: {
      scenario: "education",
      title: "Учебная задача",
      fields: [
        { label: "Инструмент ученика", value: "гитара" },
        { label: "Уровень", value: "начальный" },
        { label: "Цель урока", value: "сыграть куплет и припев с кликом" },
        { label: "Сложность результата", value: "проще оригинала" },
        { label: "Кому выдать", value: "ученику и преподавателю" },
      ],
    },
    legalConsent: { accepted: true, text: "Материал используется для приватного урока и домашней практики.", acceptedAt: "2026-09-09T12:00:00+04:00" },
    dataRetention: { sourceDeleted: false, resultsDeleted: false, retentionNote: "Учебные материалы можно удалить после урока." },
  },
  {
    id: "education-ensemble-demo",
    name: "School Hall: ансамбль учеников",
    scenario: "education",
    processingGoal: processingGoals.find((goal) => goal.id === "lesson-ensemble")!,
    upload: { id: "upload-ensemble-demo", fileName: "school-hall-demo.wav", format: "DEMO", durationSeconds: 196, quality: "medium", sourceNote: "Демо без реального аудиофайла." },
    studentProfile: { name: "Группа 5Б", instrument: "ансамбль", level: "средний", ageGroup: "11-13", notationReading: "простые ноты", chordKnowledge: "D, G, A, Bm", homeInstrument: "гитара или клавиши" },
    teacherProfile: { name: "Оксана", format: "школьный ансамбль", focus: "сценическая версия и роли учеников" },
    classGroup: { name: "Ансамбль 5Б", studentsCount: 4, instruments: ["гитара", "клавиши", "перкуссия", "вокал"] },
    lesson: { goal: "подготовить номер к школьному концерту", homeworkFormat: "партии по ученикам + общий минус", desiredDifficulty: "близко к оригиналу" },
    assignments: [
      { id: "assignment-ensemble-1", title: "Гитара: аккорды припева", recipient: "Аня", status: "in_progress" },
      { id: "assignment-ensemble-2", title: "Клавиши: hook припева", recipient: "Миша", status: "assigned" },
      { id: "assignment-ensemble-3", title: "Перкуссия: пульс и стоп", recipient: "Соня", status: "ready_for_concert" },
    ],
    versions: [
      version("ensemble-original", "Оригинал", "original", ["Исходная песня."]),
      version("ensemble-main", "Ансамблевая", "ensemble", ["Песня разложена на 4 учебные партии.", "Coda отмечена для проверки."]),
    ],
    currentVersionId: "ensemble-main",
    processing: readyProcessing("job-ensemble-demo"),
    analysis: ensembleAnalysis,
    stagePack: { id: "stage-ensemble-demo", versionId: "ensemble-main", artifacts: artifacts("education") },
    reviewIssues: [
      { id: "issue-coda-41", title: "Повтор в coda", sectionId: "ensemble-coda", bar: 41, part: "Ансамбль", reason: "Найдена нелинейная концовка с повтором последней строки.", status: "uncertain", confidence: 0.61 },
      { id: "issue-vocal-25", title: "Второй голос в припеве", sectionId: "ensemble-chorus", bar: 25, part: "Вокал", reason: "Интервал может быть сложным для учеников.", status: "needs_review", confidence: 0.69 },
    ],
    reviewComments: [],
    directorSuggestions: directorSuggestions.filter((suggestion) => suggestion.scenario !== "band"),
    chat: [{ id: "chat-ensemble-1", author: "director", text: "Материал хорошо ложится на ансамбль. Я бы отдельно выдал роли и сделал крупный сценический вид припева.", createdAt: "2026-09-09T12:09:00+04:00" }],
    changeLog: [{ id: "change-ensemble-1", title: "Создана ансамблевая версия", description: "Материал разложен на учеников и отмечена coda.", createdAt: "2026-09-09T12:10:00+04:00", actor: "AI-директор" }],
    shareRecipients: educationRecipients,
    shareLinks: [],
    exportBundles: [{ id: "zip-ensemble", label: "Пакет ансамбля", filesCount: 11, status: "ready" }],
    costEstimate: cost("high", 10),
    setupSnapshot: {
      scenario: "education",
      title: "Ансамблевая задача",
      fields: [
        { label: "Инструменты", value: "гитара, клавиши, перкуссия, вокал" },
        { label: "Количество партий", value: "4" },
        { label: "Цель урока", value: "подготовить номер к школьному концерту" },
        { label: "Сложность результата", value: "близко к оригиналу" },
        { label: "Кому выдать", value: "ансамблю и преподавателю" },
      ],
    },
    legalConsent: { accepted: true, text: "Материал используется для приватной школьной подготовки.", acceptedAt: "2026-09-09T12:00:00+04:00" },
    dataRetention: { sourceDeleted: false, resultsDeleted: false, retentionNote: "Материалы можно удалить после концерта." },
  },
];
